### ISSUE TITLE
Departure is sometimes on 2 lines

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-mobile#106]
It seems to be only when their is no arrival and that Departure name is short.

![screenshot_2015-07-10-20-26-35_resized](https://cloud.githubusercontent.com/assets/4418840/8629358/f1f92392-275a-11e5-8426-003e2464e6fb.png)

**Comment by SBats** [comment]
Can't replicate on our android devices. Which one do you use ? (screen-size, Android version, browser ?)

**Comment by camillemonchicourt** [comment]
It dont seem to be on all treks. Only those that have short departures and no arrival...

Maybe try on the same TREK as on this example. SENTIER DE DECOUVERTE DU BOCAGE

LG G2, Android 4.4.2. I think it is 1080 x 1920 pixels.

**Comment by camillemonchicourt** [comment]
Same on V2.1 we are actually testing : 

![screenshot_2015-10-26-15-45-26_resized](https://cloud.githubusercontent.com/assets/4418840/10732121/d182bb08-7bf8-11e5-8229-85f21db78f2a.png)

**Comment by camillemonchicourt** [comment]
Isn't it the same problem that was just fixed for duration in CCG V1 ?
And that I also still have in V2 GTE for balisage :

![screenshot_2016-01-05-14-45-29_resized](https://cloud.githubusercontent.com/assets/4418840/12116611/5764f282-b3bb-11e5-8363-8ba6cbb7816e.png)

**Comment by SBats** [comment]
Are you with the stock browser or a Chrome browser on your test phone ?
If it's the stock one, could you check if there's this option in your settings :
settings > advanced > auto-fit pages

if so, could you try whith it disabled please ? I just want to know what cause the issue exactly. Because the fix used for another part of the page might create problems with long text (no-wrapping =  text outside of the page if too long)

**Comment by camillemonchicourt** [comment]
Sorry, dont have this setting in my stock browser.
LG-G2, Android 4.4.2

**Comment by camillemonchicourt** [comment]
Not reproduced anymore and seems to be specific to just a few devices.
Reopen if it happens again.
