### ISSUE TITLE
Bug in trek sort by distance

### ISSUE THREAD

**Issue by gutard** [makinacorpus/Geotrek-mobile#111]

**Comment by gutard** [comment]
Resolution time will depend on ability to reproduce

**Comment by camillemonchicourt** [comment]
Actually I already noticed this bug when we did the first tests of Geotrek-mobile. 
All treks were well sorted by GPS distance except the new one that we had just added to do our test. I thought that it was because it was a new trek just added but we forgot this one as we couldnt really reproduce it.

Last week it happened again with Rando Ecrins mobile. 

I launched the app while in the national park. The first trek was 1.85 km far and the second one was 11.30 km far :

![screenshot_2015-09-10-10-12-37](https://cloud.githubusercontent.com/assets/4418840/9860822/b4bb61cc-5b2e-11e5-8413-ba2d42dd6e21.png)

A bit later in the list, there was one that should be second in the list (Le Pic Morgon, 3.88 km far) : 

![screenshot_2015-09-10-10-10-00](https://cloud.githubusercontent.com/assets/4418840/9860847/d270926e-5b2e-11e5-96ca-f8010a046f86.png)


Then another one later in the list, the one supposed to be the third one (Les Aiguilles de Chabrieres - 6,43 km)


![screenshot_2015-09-10-10-12-14](https://cloud.githubusercontent.com/assets/4418840/9860850/da08aae8-5b2e-11e5-9cf1-51fc01cbbde7.png)


And 2 other treks at the end of the list...


![screenshot_2015-09-10-10-12-23](https://cloud.githubusercontent.com/assets/4418840/9860853/dd7fc288-5b2e-11e5-9bd7-cbc305f07ca6.png)


These 5 treks that are not in good order are not particulary new. And it just happened when I was near these treks. It dont happen again when I am home and far from these treks...

#################

OK I understand now... It only happens with treks that are near user (less than 10 km) so you will never reproduce it if you launch Rando Ecrins mobile from Toulouse. :-)

It must be a problem with decimals and values that are below 10...
Look at the order of treks : 1.85 km then 11.30 then 29.49 then 3.88 then 59.64 then 6.43 then 66.41 then 8.42 then 9.38...

**Comment by gutard** [comment]
Thanks a lot for all this information. I'm pretty sure the sort is in alphabetic order, not numeric one. Should be easy to fix.
