### ISSUE TITLE
Change departure and arrival markers

### ISSUE THREAD

**Issue by SBats** [makinacorpus/Geotrek-mobile#137]
I've tried with rando version markers :
![screenshot-0 0 0 0 9000 2015-10-26 18-17-05](https://cloud.githubusercontent.com/assets/3982958/10737099/a7117af4-7c10-11e5-9cd9-43c61a2a7b77.png)

It's not really clear so I've tried those versions :
![screenshot-0 0 0 0 9000 2015-10-26 18-31-08](https://cloud.githubusercontent.com/assets/3982958/10737104/b3357e34-7c10-11e5-83e5-e79b25e7729d.png)

The screenshot is not optimal but it reflect a use case so...

![capture du 2015-10-26 18-41-31](https://cloud.githubusercontent.com/assets/3982958/10737223/471478d0-7c11-11e5-9f95-bba0daeae151.png)

What do you think @camillemonchicourt ?

**Comment by camillemonchicourt** [comment]
OK interesting. 
I see a few points : 
* As there is Departure and Arrival, I think it is not good to also display a purple marker for the trek. It brings confusion in the first screenshot and is not good for readability. 
* I also think that markers should be dedicated to one type of content (Services).
* That's a reason why I prefer the first option with signs rather than markers. Also signs for departure and arrival are the most easy to understand.
* I also understand that you are able to detect when arrival and arrival are at the same place to display 1 symbol rather that 2 that we dont read easily. 
In this case, why not do a third one with signs that would be something like this ?
![departure-arrival](https://cloud.githubusercontent.com/assets/4418840/10752603/1873db04-7c8b-11e5-8018-62b1a3824d23.jpg)

**Comment by SBats** [comment]
Ok, so :

- The purple marke is displayed because it's a live refresh on the web preview. On the mobile phone they're not displayed because you can't arrive directly on a detail map view.

- This type of marker is not used for services only. It's already used for trek markers. In general a graphic consistensy is better. Color can be meaningfull enough to dissociate type of markers in my opinion.

- This example is the worst case because it display a trek which has the departure and arrival really close. In fact it should be a loop. We already use a cumulativ icon when it's a loop, but if the data is not well done (meaning it should be a loop type but it isn't), we can't prevent the app to display both markers really close. It's the same thing on RANDO.
Here is the loop sign version :
![screenshot-rando-pnc makina-corpus net 2015-10-28 11-31-50](https://cloud.githubusercontent.com/assets/3982958/10785942/86f79eee-7d67-11e5-8caa-7762002b7d85.png)


- My point here was mostly that the signs version is not cleary readable on the IGN background, whereas the pin version is. It would be good to have a very distinctive marker for those, but as long as we don't have a designer to work on it, it's kinda hard to spend too much time on it.

**Comment by camillemonchicourt** [comment]
* OK about the purple marker, good ! 
* OK about other points, I understand your point of view. 
* OK about loop, and the case where departure and arrival are very near. 
* Nice sign loop version
* I still prefer the sign version for departure and arrival but if it is OK fro you to wait with this issue, I prefer to ask my colleagues that will be there tomorrow.

**Comment by SBats** [comment]
Yeah ok no worries. For now I put the signs versions to remove the Loire Atlantic versions and be consistent with rando and we can discuss this further when your collegue is here :)

**Comment by camillemonchicourt** [comment]
Great and perfect ! Thanks.
